pipeline:
  build:
    image: ${IMAGE}
    secrets: [ARTIFACT_SSH_KEY]
    commands:
      - cd ImageMagick
      - ./build.sh $(uname -m)
      - ../tools/upload.sh ImageMagick-$(uname -m).tar.gz
    volumes:
      - /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static
matrix:
  IMAGE:
    - armv7/armhf-debian:8
    - debian:8