---
kind: pipeline
name: bind9-arm

platform:
  os: linux
  arch: arm

steps:
- name: build
  image: debian:buster-backports
  commands:
  - ./build.sh bind9

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source: bind9/*.tar.gz
    strip_components: 1
    target: /home/artifact/repo/3rdparty/${DRONE_BUILD_NUMBER}-arm
    timeout: 2m
    username: artifact
  when:
    status:
    - failure
    - success

---
kind: pipeline
name: bind9-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: debian:buster-backports
  commands:
  - ./build.sh bind9

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source: bind9/*.tar.gz
    strip_components: 1
    target: /home/artifact/repo/3rdparty/${DRONE_BUILD_NUMBER}-amd64
    timeout: 2m
    username: artifact
  when:
    status:
    - failure
    - success

...
