---
kind: pipeline
name: php7-arm

platform:
  os: linux
  arch: arm

steps:
- name: build
  image: syncloud/build-deps-arm
  commands:
  - ./build.sh php7

- name: upload
  image: syncloud/build-deps-arm
  commands:
  - cd php7
  - "../upload.sh php7-*.tar.gz"
  environment:
    ARTIFACT_SSH_KEY:
      from_secret: ARTIFACT_SSH_KEY

---
kind: pipeline
name: php7-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: syncloud/build-deps-amd64
  commands:
  - ./build.sh php7

- name: upload
  image: syncloud/build-deps-amd64
  commands:
  - cd php7
  - "../upload.sh php7-*.tar.gz"
  environment:
    ARTIFACT_SSH_KEY:
      from_secret: ARTIFACT_SSH_KEY

...
