pipeline:
  build:
    image: buildpack-deps
    secrets: [secret_test]
    commands:
      - git status
      - cd ImageMagick
      - echo $$secret_test
      - sleep 100
      #- ./build.sh $(uname -m)