platform: linux/${arch}

clone:
  git:
    image: syncloud/drone-git-${arch}
    depth: 50
    
pipeline:
  build:
    image: syncloud/rootfs-${arch}
    commands:
      - ./build.sh ${project}
      
  upload:
    image: syncloud/rootfs-${arch}
    secrets: [ARTIFACT_SSH_KEY]
    commands:
      - cd ${project}
      - ../upload.sh ${project}-$(uname -m).tar.gz

matrix:
  arch:
    - arm
    - amd64
  project: 
#   - ImageMagick
#   - PyYAML
#   - asterisk
#   - dovecot
#   - git
#   - mariadb
#   - nginx
#   - nodejs
#   - openldap
#   - openssl
#   - php
#   - php7
#   - postfix
   - postgresql
#   - python
#   - redis
#   - rsyslog
#   - ruby
#   - uwsgi
#   - certbot
