platform: ${platform}

clone:
  git:
    image: ${git}
    depth: 50
    
pipeline:
  build:
    image: ${container}
    secrets: [ARTIFACT_SSH_KEY]
    commands:
      - ./build.sh ${PROJECT}

matrix:
  PROJECT:
    #- ImageMagick
    - PyYAML
    #- asterisk
    #- dovecot
    #- git
    #- mariadb
    #- nginx
    #- nodejs
    #- openldap
    #- openssl
    #- php
    #- php7
    #- postfix
    #- postgresql
    #- python
    #- redis
    #- rsyslog
    #- ruby
    #- uwsgi
  include:
    - platform: linux/arm
      container: armv7/armhf-debian:8
      git: syncloud/armhf-drone-git
    - platform: linux/amd64
      container: debian:8
      git: plugins/git
