---
kind: pipeline
name: php7-arm

platform:
  os: linux
  arch: arm

steps:
- name: build
  image: syncloud/build-deps-arm
  commands:
  - ./build.sh php7

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source: php7/*.tar.gz
    strip_components: 1
    target: /home/artifact/repo/3rdparty/${DRONE_BUILD_NUMBER}-arm
    timeout: 2m
    username: artifact
  when:
    status:
    - failure
    - success

---
kind: pipeline
name: php7-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: syncloud/build-deps-amd64
  commands:
  - ./build.sh php7

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source: php7/*.tar.gz
    strip_components: 1
    target: /home/artifact/repo/3rdparty/${DRONE_BUILD_NUMBER}-amd64
    timeout: 2m
    username: artifact
  when:
    status:
    - failure
    - success

...
