---
kind: pipeline
name: bind9-arm

platform:
  os: linux
  arch: arm

steps:
- name: build
  image: syncloud/build-deps-arm
  commands:
  - ./build.sh bind9

- name: upload
  image: syncloud/build-deps-arm
  commands:
  - cd bind9
  - "../upload.sh bind9-*.tar.gz"
  environment:
    ARTIFACT_SSH_KEY:
      from_secret: ARTIFACT_SSH_KEY

---
kind: pipeline
name: bind9-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: syncloud/build-deps-amd64
  commands:
  - ./build.sh bind9

- name: upload
  image: syncloud/build-deps-amd64
  commands:
  - cd bind9
  - "../upload.sh bind9-*.tar.gz"
  environment:
    ARTIFACT_SSH_KEY:
      from_secret: ARTIFACT_SSH_KEY

...
