---
kind: pipeline
name: postgresql-10-arm

platform:
  os: linux
  arch: arm

steps:
- name: build
  image: syncloud/build-deps-arm
  commands:
  - ./build.sh postgresql-10

- name: upload
  image: syncloud/build-deps-arm
  commands:
  - cd postgresql-10
  - "../upload.sh postgresql-10-*.tar.gz"
  environment:
    ARTIFACT_SSH_KEY:
      from_secret: ARTIFACT_SSH_KEY

---
kind: pipeline
name: postgresql-10-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: syncloud/build-deps-amd64
  commands:
  - ./build.sh postgresql-10

- name: upload
  image: syncloud/build-deps-amd64
  commands:
  - cd postgresql-10
  - "../upload.sh postgresql-10-*.tar.gz"
  environment:
    ARTIFACT_SSH_KEY:
      from_secret: ARTIFACT_SSH_KEY

...
