pipeline:
  build:
    image: buildpack-deps
    secrets: [ARTIFACT_SSH_KEY]
    commands:
      - git status
      - cd ImageMagick
      - ../tools/upload.sh build.sh
      #- ./build.sh $(uname -m)