platform: ${platform}

clone:
  git:
    image: ${git}
    depth: 50
    
pipeline:
  build:
    image: ${container}
    secrets: [ARTIFACT_SSH_KEY]
    commands:
      - ./build.sh ${project}

matrix:
  include:
#    - platform: linux/arm
#      container: armv7/armhf-debian:8
#      git: syncloud/armhf-drone-git
#      project: ImageMagick
#    - platform: linux/amd64
#      container: debian:8
#      git: plugins/git
#      project: ImageMagick
#    - platform: linux/arm
#      container: armv7/armhf-debian:8
#      git: syncloud/armhf-drone-git
#      project: PyYAML
#    - platform: linux/amd64
#      container: debian:8
#      git: plugins/git
#      project: PyYAML
#    - platform: linux/arm
#      container: armv7/armhf-debian:8
#      git: syncloud/armhf-drone-git
#      project: asterisk
#    - platform: linux/amd64
#      container: debian:8
#      git: plugins/git
#      project: asterisk
#    - platform: linux/arm
#      container: armv7/armhf-debian:8
#      git: syncloud/armhf-drone-git
#      project: dovecot
#    - platform: linux/amd64
#      container: debian:8
#      git: plugins/git
#      project: dovecot
#    - platform: linux/arm
#      container: armv7/armhf-debian:8
#      git: syncloud/armhf-drone-git
#      project: git
#    - platform: linux/amd64
#      container: debian:8
#      git: plugins/git
#      project: git
#    - platform: linux/arm
#      container: armv7/armhf-debian:8
#      git: syncloud/armhf-drone-git
#      project: mariadb
#    - platform: linux/amd64
#      container: debian:8
#      git: plugins/git
#      project: mariadb
    - platform: linux/arm
      container: armv7/armhf-debian:8
      git: syncloud/armhf-drone-git
      project: nginx
    - platform: linux/amd64
      container: debian:8
      git: plugins/git
      project: nginx
#    - platform: linux/arm
#      container: armv7/armhf-debian:8
#      git: syncloud/armhf-drone-git
#      project: nodejs
#    - platform: linux/amd64
#      container: debian:8
#      git: plugins/git
#      project: nodejs
#    - platform: linux/arm
#      container: armv7/armhf-debian:8
#      git: syncloud/armhf-drone-git
#      project: openldap
#    - platform: linux/amd64
#      container: debian:8
#      git: plugins/git
#      project: openldap
#    - platform: linux/arm
#      container: armv7/armhf-debian:8
#      git: syncloud/armhf-drone-git
#      project: openssl
#    - platform: linux/amd64
#      container: debian:8
#      git: plugins/git
#      project: openssl
#    - platform: linux/arm
#      container: armv7/armhf-debian:8
#      git: syncloud/armhf-drone-git
#      project: php
#    - platform: linux/amd64
#      container: debian:8
#      git: plugins/git
#      project: php
#    - platform: linux/arm
#      container: armv7/armhf-debian:8
#      git: syncloud/armhf-drone-git
#      project: php7
#    - platform: linux/amd64
#      container: debian:8
#      git: plugins/git
#      project: php7
#    - platform: linux/arm
#      container: armv7/armhf-debian:8
#      git: syncloud/armhf-drone-git
#      project: postfix
#    - platform: linux/amd64
#      container: debian:8
#      git: plugins/git
#      project: postfix
#    - platform: linux/arm
#      container: armv7/armhf-debian:8
#      git: syncloud/armhf-drone-git
#      project: postgresql
#    - platform: linux/amd64
#      container: debian:8
#      git: plugins/git
#      project: postgresql
#    - platform: linux/arm
#      container: armv7/armhf-debian:8
#      git: syncloud/armhf-drone-git
#      project: python
#    - platform: linux/amd64
#      container: debian:8
#      git: plugins/git
#      project: python
#    - platform: linux/arm
#      container: armv7/armhf-debian:8
#      git: syncloud/armhf-drone-git
#      project: redis
#    - platform: linux/amd64
#      container: debian:8
#      git: plugins/git
#      project: redis
#    - platform: linux/arm
#      container: armv7/armhf-debian:8
#      git: syncloud/armhf-drone-git
#      project: rsyslog
#    - platform: linux/amd64
#      container: debian:8
#      git: plugins/git
#      project: rsyslog
#    - platform: linux/arm
#      container: armv7/armhf-debian:8
#      git: syncloud/armhf-drone-git
#      project: ruby
#    - platform: linux/amd64
#      container: debian:8
#      git: plugins/git
#      project: ruby
#    - platform: linux/arm
#      container: armv7/armhf-debian:8
#      git: syncloud/armhf-drone-git
#      project: uwsgi
#    - platform: linux/amd64
#      container: debian:8
#      git: plugins/git
#      project: uwsgi
