---
kind: pipeline
name: postgresql-arm

platform:
  os: linux
  arch: arm

steps:
- name: build
  image: syncloud/build-deps-arm
  commands:
  - ./build.sh postgresql

- name: upload
  image: syncloud/build-deps-arm
  commands:
  - cd postgresql
  - "../upload.sh postgresql-*.tar.gz"
  environment:
    ARTIFACT_SSH_KEY:
      from_secret: ARTIFACT_SSH_KEY

---
kind: pipeline
name: postgresql-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: syncloud/build-deps-amd64
  commands:
  - ./build.sh postgresql

- name: upload
  image: syncloud/build-deps-amd64
  commands:
  - cd postgresql
  - "../upload.sh postgresql-*.tar.gz"
  environment:
    ARTIFACT_SSH_KEY:
      from_secret: ARTIFACT_SSH_KEY

...
