pipeline:
  build:
    image: ${IMAGE}
    secrets: [ARTIFACT_SSH_KEY]
    commands:
      - ./build.sh ${PROJECT}
    volumes:
      - /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static
matrix:
  PROJECT:
    #- ImageMagick
    #- PyYAML
    #- asterisk
    #- dovecot
    #- git
    #- mariadb
    #- nginx
    #- nodejs
    - openldap
    - openssl
    #- php
    - php7
    - postfix
    #- postgresql
    - python
    #- redis
    - rsyslog
    - ruby
    - uwsgi
  IMAGE:
    - armv7/armhf-debian:8
    - debian:8