pipeline:
  build:
    #image: buildpack-deps
    image: ioft/armhf-ubuntu:trusty
    secrets: [ARTIFACT_SSH_KEY]
    commands:
      - cd ImageMagick
      #- ./build.sh $(uname -m)
      #- ../tools/upload.sh ImageMagick-$(uname -m).tar.gz
  volume:
    - /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static