pipeline:
  build:
    image: buildpack-deps
    secrets: [ARTIFACT_SSH_KEY]
    commands:
      - cd ImageMagick
      - ./build.sh $(uname -m)
      - ../tools/upload.sh ImageMagick-$(uname -m).tar.gz 